In [1]:
from library import *
import timeit

In [ ]:
s = 10
A = np.random.randint(-4, 4, size=(s, s))
print('size:', A.shape)
print(A)
S = np.dot(A.T, A)

size : (10, 10)
[[ 2 -1 -4 -2 -4 -1  0 -4 -1 -4]
 [ 1 -2  3 -2  3  2 -1  3  0  2]
 [-3  3  1 -2  2 -2  3 -2  3  1]
 [ 3 -4 -1 -1 -2 -4 -1  0 -4 -1]
 [-2 -1  1  0  0  2  0  2  0  3]
 [ 3  0  0  1  1  2 -1 -2 -1 -2]
 [-3 -3  3  2  3 -3 -2 -3 -1 -4]
 [ 3 -3 -1 -2  1  3  0  1 -2 -4]
 [ 3  1 -3 -3  3 -2 -4  1 -3 -2]
 [ 2 -4 -4 -1  1 -1  1  2 -4  3]]


In [4]:
print('Test if A @ A.T is symetric:')
print(is_sym(S))

Test if A @ A.T is symetric:
True


In [7]:
print('For matrix', A.shape)
start = timeit.default_timer()
detA = determinant_naive(A)
stop = timeit.default_timer()
print('determinant of A (naive method):', detA)
print(f'Computed in {stop - start:.2f} seconds')


start = timeit.default_timer()
detA = determinant_gauss(A)
stop = timeit.default_timer()
print('determinant of A (gaussian method):', detA)
print(f'Computed in {stop - start:.2f} seconds')


start = timeit.default_timer()
detA = np.linalg.det(A)
stop = timeit.default_timer()
print('determinant of A (numpy linalg mehtod):', detA)
print(f'Computed in {stop - start:.2f} seconds')

For matrix (10, 10)
determinant of A (naive method): -6189062
Computed in 1.67 seconds
determinant of A (gaussian method): -6189061.999999957
Computed in 0.00 seconds
determinant of A (numpy linalg mehtod): -6189062.000000012
Computed in 0.00 seconds


In [9]:
s2 = 1000
A2 = np.random.rand(s2, s2) / 10
print('size:', A2.shape)
print(A2)

size: (1000, 1000)
[[0.0161447  0.03222738 0.04812303 ... 0.04285125 0.07196332 0.01828996]
 [0.03351892 0.04964823 0.04080698 ... 0.05835398 0.02438671 0.04990895]
 [0.06276807 0.07926495 0.00142676 ... 0.00367016 0.04887352 0.07981764]
 ...
 [0.06917067 0.02333461 0.04655218 ... 0.02690018 0.01068992 0.08187185]
 [0.01900808 0.01026261 0.09850353 ... 0.03970555 0.02096216 0.09800566]
 [0.0069362  0.0770377  0.04677338 ... 0.00463869 0.0302453  0.08051035]]


In [10]:
print('For matrix', A2.shape)
start = timeit.default_timer()
detA2 = determinant_gauss(A2)
stop = timeit.default_timer()
print('determinant of A (gaussian method):', detA2)
print(f'Computed in {stop - start:.2f} seconds')


start = timeit.default_timer()
detA2 = np.linalg.det(A2)
stop = timeit.default_timer()
print('determinant of A (numpy linalg mehtod):', detA2)
print(f'Computed in {stop - start:.2f} seconds')

For matrix (1000, 1000)
determinant of A (gaussian method): 2.523769182753283e-257
Computed in 0.84 seconds
determinant of A (numpy linalg mehtod): 2.5237691829099018e-257
Computed in 0.01 seconds


In [11]:
print('Test if A @ A.T is positive definite:')
print(is_def_pos_sylvester(S))

Test if A @ A.T is positive definite:
True


In [12]:
print('Test the inverse of A with gaussian with A @ inv(A) == Id:')
invA = inverse_gauss(A)
print(np.round(np.dot(invA, A) + 0.0001, 3))

Test the inverse of A with gaussian with A @ inv(A) == Id:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
print('Test Cholesky algorithme on S = A @ A.T:')
L = cholesky(S)
if np.linalg.norm(np.dot(L, L.T) - S) < 0.001:
    print(True)
else:
    print(False)

Test Cholesky algorithme on S = A @ A.T:
True


In [ ]:
s = 4
A = np.random.randint(-4, 4,size=(s, s))
print('size:', A.shape)
print(A)

size : (4, 4)
[[-1 -4 -2 -2]
 [ 2 -1 -4  3]
 [ 3  2 -1  1]
 [-1 -2  3  1]]


In [ ]:
print('Test the diagonalization algorithm with power iteration method')
print('For matrix', A.shape)
A_eigvals, A_eigvect = eigen(A)
while len(A_eigvals) != s:
    A = np.random.randint(-4, 4, size=(s, s))
    A_eigvals, A_eigvect = eigen(A)
print('Eigen value:', A_eigvals)

Test the diagonalization algorithm with power iteration method
For matrix (10, 10)
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diagonalizable
Matrix is not diag

In [ ]:
s = 500
A = np.random.rand(s, s) / 10
S = np.dot(A.T, A)
print('size:', S.shape)
print('Test the diagonalization algorithm with power iteration method')
print('For matrix', S.shape)

start = timeit.default_timer()
S_eigvals, S_eigvect = eigen(S)
stop = timeit.default_timer()
print(f'Computed in {stop - start:.2f} seconds')

size : (500, 500)
Test the diagonalizable algorithm with power iteration method
For matrix (500, 500)
time : 8.616561934000856 secs


In [ ]:
print('eigen values:\n', S_eigvals)
S_eigvals2 = np.linalg.eigvals(S)
print('eigen values with numpy linalg:\n', S_eigvals2)
if sum(S_eigvals) - S_eigvals2.sum() < 1:
    print('True')
else:
    print('False')

eigen values :
 [np.float64(627.60554), np.float64(1.61399), np.float64(1.59056), np.float64(1.56296), np.float64(1.55264), np.float64(1.52398), np.float64(1.51657), np.float64(1.50587), np.float64(1.4785), np.float64(1.4698), np.float64(1.45033), np.float64(1.46516), np.float64(1.42926), np.float64(1.41138), np.float64(1.40105), np.float64(1.39514), np.float64(1.37426), np.float64(1.36658), np.float64(1.34382), np.float64(1.34351), np.float64(1.32606), np.float64(1.3243), np.float64(1.30319), np.float64(1.29092), np.float64(1.28427), np.float64(1.27858), np.float64(1.27521), np.float64(1.26202), np.float64(1.2477), np.float64(1.23939), np.float64(1.23619), np.float64(1.22847), np.float64(1.22448), np.float64(1.21479), np.float64(1.20632), np.float64(1.1986), np.float64(1.19277), np.float64(1.17642), np.float64(1.16325), np.float64(1.15569), np.float64(1.14862), np.float64(1.13448), np.float64(1.13033), np.float64(1.12747), np.float64(1.11859), np.float64(1.10889), np.float64(1.108), n